### ISSUE TITLE
Repository clone

### ISSUE THREAD

**Issue by aprilbom** [aprilbom/Project#1]
여러분 새 repository 에서 초대 보냈어욤 이게 폴더 이름이 Project 입니다 (Project1 이 아니라!!)

git bash 기준으로
workspace로 지정할 폴더 가서!! git clone 하면 됨!  (사진 참조)

git bash 로 하고나서 Github GUI 에서는 File - add local Repository 해서 workspace 내에 있는 클론해온 "Project" 폴더 선택 (Project 폴더@!!! 선택해야함!!!! workspace 경로 설정하면 안됨 workspace 안에 있는 Project 폴더@!!!!!)
![1](https://user-images.githubusercontent.com/44661703/48817076-0a5cf700-ed88-11e8-9635-3b292265f15e.png)

**Comment by jinnjuu** [comment]
성공한 것 같아요 ~!
